<?php

namespace Database\Seeders;

use App\Models\Keyword;
use Illuminate\Database\Seeder;

class AddKeywordTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $keywords = [
            ['id' => 1, 'keyword' => 'áo', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 2, 'keyword' => 'quần', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 3, 'keyword' => 'giày', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 4, 'keyword' => 'dép', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 5, 'keyword' => 'túi', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 6, 'keyword' => 'váy', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 7, 'keyword' => 'dầm', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 8, 'keyword' => 'thắt lưng', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 9, 'keyword' => 'nịt', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 10, 'keyword' => 'tất', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 11, 'keyword' => 'khoác', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 12, 'keyword' => 'mũ', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 13, 'keyword' => 'đồng hồ', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 14, 'keyword' => 'vòng', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 15, 'keyword' => 'lắc', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 16, 'keyword' => 'dây chuyền', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 17, 'keyword' => 'kính', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 18, 'keyword' => 'gương', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 19, 'keyword' => 'thời trang', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 20, 'keyword' => 'fashion', 'category_id' => CATEGORY_ID_FASHION],
            ['id' => 21, 'keyword' => 'son', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 22, 'keyword' => 'phấn', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 23, 'keyword' => 'tẩy trang', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 24, 'keyword' => 'khăn', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 25, 'keyword' => 'nước hoa', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 26, 'keyword' => 'xịt', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 27, 'keyword' => 'thơm', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 28, 'keyword' => 'dưỡng tóc', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 29, 'keyword' => 'dưỡng da', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 30, 'keyword' => 'dưỡng môi', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 31, 'keyword' => 'mặt nạ', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 32, 'keyword' => 'cọ', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 33, 'keyword' => 'mút', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 34, 'keyword' => 'chì', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 35, 'keyword' => 'beauty', 'category_id' => CATEGORY_ID_COSMETIC],
            ['id' => 36, 'keyword' => 'nồi', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 37, 'keyword' => 'niêu', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 38, 'keyword' => 'song', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 40, 'keyword' => 'chảo', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 41, 'keyword' => 'chống', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 42, 'keyword' => 'lò', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 43, 'keyword' => 'chén', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 44, 'keyword' => 'bát', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 45, 'keyword' => 'dĩa', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 46, 'keyword' => 'đĩa', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 47, 'keyword' => 'muỗng', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 48, 'keyword' => 'thìa', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 49, 'keyword' => 'tủ lạnh', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 50, 'keyword' => 'bàn là', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 51, 'keyword' => 'quạt', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 52, 'keyword' => 'bàn', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 53, 'keyword' => 'ghế', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 54, 'keyword' => 'thảm', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 55, 'keyword' => 'chăn', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 56, 'keyword' => 'ga', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 57, 'keyword' => 'gối', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 58, 'keyword' => 'đệm', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 59, 'keyword' => 'cốc', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 60, 'keyword' => 'ly', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 61, 'keyword' => 'kệ', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 62, 'keyword' => 'giá', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 63, 'keyword' => 'rèm', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 64, 'keyword' => 'khăn', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 65, 'keyword' => 'chiếu', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 66, 'keyword' => 'cửa', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 67, 'keyword' => 'khay', 'category_id' => CATEGORY_ID_HOUSEWARE],
            ['id' => 68, 'keyword' => 'thịt', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 69, 'keyword' => 'chuột', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 70, 'keyword' => 'tôm', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 71, 'keyword' => 'cua', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 72, 'keyword' => 'sò', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 73, 'keyword' => 'ốc', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 74, 'keyword' => 'hến', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 75, 'keyword' => 'ghẹ', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 76, 'keyword' => 'chim', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 77, 'keyword' => 'baba', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 78, 'keyword' => 'rùa', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 79, 'keyword' => 'bò', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 80, 'keyword' => 'trâu', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 81, 'keyword' => 'gà', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 82, 'keyword' => 'vịt', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 83, 'keyword' => 'ngan', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 84, 'keyword' => 'ngỗng', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 85, 'keyword' => 'bánh', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 86, 'keyword' => 'mì', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 87, 'keyword' => 'sửa', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 88, 'keyword' => 'đường', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 89, 'keyword' => 'trà', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 90, 'keyword' => 'ngọt', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 91, 'keyword' => 'chiên', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 92, 'keyword' => 'mắm', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 93, 'keyword' => 'tré', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 94, 'keyword' => 'tre', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 95, 'keyword' => 'lộn', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 96, 'keyword' => 'chiên', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 97, 'keyword' => 'dầu', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 98, 'keyword' => 'cam', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 99, 'keyword' => 'quýt', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 100, 'keyword' => 'xoài', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 101, 'keyword' => 'đào', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 102, 'keyword' => 'ổi', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 103, 'keyword' => 'mận', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 104, 'keyword' => 'táo', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 105, 'keyword' => 'dưa', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 106, 'keyword' => 'hấu', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 107, 'keyword' => 'sung', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 108, 'keyword' => 'chuối', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 109, 'keyword' => 'mít', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 110, 'keyword' => 'mẹt', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 111, 'keyword' => 'sầu riêng', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 112, 'keyword' => 'một nắng', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 113, 'keyword' => 'mực', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 114, 'keyword' => 'bạch tuộc', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 115, 'keyword' => 'sấu', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 116, 'keyword' => 'chanh', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 117, 'keyword' => 'dứa', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 118, 'keyword' => 'dừa', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 119, 'keyword' => 'chát', 'category_id' => CATEGORY_ID_EAT],
            ['id' => 120, 'keyword' => 'khỏe', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 121, 'keyword' => 'mạnh', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 122, 'keyword' => 'thuốc', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 123, 'keyword' => 'mạnh', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 124, 'keyword' => 'cân', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 125, 'keyword' => 'tăng', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 126, 'keyword' => 'giảm', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 127, 'keyword' => 'gan', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 128, 'keyword' => 'thận', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 129, 'keyword' => 'tim', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 130, 'keyword' => 'đo', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 131, 'keyword' => 'dinh dưỡng', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 132, 'keyword' => 'năng', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 133, 'keyword' => 'lượng', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
            ['id' => 134, 'keyword' => 'trà', 'category_id' => CATEGORY_ID_FUNCTION_FOOD],
        ];

        foreach ($keywords as $keyword) {
            Keyword::insert($keyword);
        }
    }
}
